"""initial

Revision ID: 076d59e9faea
Revises: 
Create Date: 2026-02-23 11:43:40.506022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076d59e9faea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_logs_device_employee_id'), ['device_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_logs_direction'), ['direction'], unique=False)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'department', ['department_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_employee_code'), ['employee_code'], unique=False)
        batch_op.create_foreign_key(None, 'department', ['managed_department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_employee_code'))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('face_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_logs_direction'))
        batch_op.drop_index(batch_op.f('ix_face_logs_device_employee_id'))

    # ### end Alembic commands ###
